services:
  auto-ripping:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-ripping
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - ISO_OUT_DIR=/iso-output
      - MP4_OUT_DIR=/mp4-output
      - DISC_DRIVE=/disc-drive
      - MKV_OUT_DIR=/mkv-output
    volumes:
      - type: bind
        source: "~/auto-rip/iso/"
        target: /iso-output/
      - type: bind
        source: "~/auto-rip/mp4/"
        target: /mp4-output/
      - type: bind
        source: ""
        target: /disc-drive/
      - type: bind
        source: "~/auto-rip/mkv/"
        target: /mkv-output/
    stdin_open: true # docker run -i (just to keep the container running, so it can be exec into)
    devices:
      - "/dev/sr0:/dev/sr0"
    privileged: true
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=$PLEX_CLAIM_CODE
      - VERSION=docker
    hostname: plexmediaserver
    network_mode: bridge
    privileged: true
    devices:
      - "/dev/sr0:/dev/sr0"
    volumes:
      - ./plexmediaserver/config:/config
      - ./plexmediaserver/transcode:/transcode
      - ./plexmediaserver/data:/data